# Generated by Django 5.0.6 on 2025-02-08 17:01

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(blank=True, choices=[('geans', 'geans'), ('jacket', 'jacket'), ('Saree', 'Saree'), ('Shirt', 'Shirt'), ('Watch', 'Watch'), ('Cricket Bat', 'Cricket Bat'), ('Football', 'Football')], max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='cetagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cetagorytype', models.CharField(blank=True, choices=[('Shirt', 'Shirt'), ('Saree', 'Saree'), ('Geans', 'Geans'), ('Football', 'Football'), ('Powder', 'Powder'), ('Cricket Bat', 'Cricket Bat'), ('Watch', 'Watch')], max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('datetime_a', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-colour_name'],
            },
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-country_name'],
            },
        ),
        migrations.CreateModel(
            name='MainMetariails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_option', models.CharField(blank=True, choices=[('jacket', 'jacket'), ('Bat', 'Bat'), ('jursey', 'jursey'), ('geans', 'geans'), ('watch', 'watch'), ('Saree', 'Saree'), ('Football', 'Football')], max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Movement_Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='range_of_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_size', models.CharField(blank=True, choices=[('Geans', 'Geans'), ('Saree', 'Saree'), ('Jacket', 'Jacket'), ('Watch', 'Watch'), ('Bat Size', 'Bat Size'), ('Shirt', 'Shirt'), ('Powder', 'Powder'), ('Jursey', 'Jursey')], max_length=100, null=True)),
                ('size_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='TypeOFJacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='warenty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_type', models.CharField(blank=True, choices=[('jacket', 'jacket'), ('watch', 'watch'), ('powder', 'powder'), ('Football', 'Football'), ('Geans', 'Geans'), ('Saree', 'Saree'), ('Shirt', 'Shirt')], max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_your_product', models.CharField(blank=True, choices=[('Saree', 'Saree'), ('Geans', 'Geans'), ('Shirt', 'Shirt'), ('T shirt', 'T shirt'), ('Watch', 'Watch'), ('Powder', 'Powder'), ('Shoo', 'Shoo'), ('Sports', 'Sports'), ('Jacket', 'Jacket')], max_length=100, null=True)),
                ('sports_Type', models.CharField(blank=True, choices=[('Football', 'Football'), ('Cricket Ball', 'Cricket Ball'), ('Cricket Bat', 'Cricket Bat'), ('Jursi', 'Jursi'), ('Boot', 'Boot'), ('Basketball', 'Basketball'), ('Baseball', 'Baseball'), ('Tennis ball', 'Tennis ball'), ('Handball', 'Handball'), ('Rink Ball', 'Rink ball'), ('Volleyball ball', 'Volleyball ball')], max_length=100, null=True)),
                ('product_title', models.CharField(blank=True, max_length=100, null=True)),
                ('display_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('font_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('quantity', models.IntegerField()),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('abailable', models.CharField(blank=True, default='is Stock', max_length=100, null=True)),
                ('eyes', models.IntegerField(blank=True, default=0, null=True)),
                ('Brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.brand')),
                ('MainMetariails', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.mainmetariails')),
                ('Movement_Watch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.movement_watch')),
                ('cetagory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.cetagory')),
                ('colour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.colour')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.country')),
                ('range_of_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.range_of_price')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.size')),
                ('team', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.team')),
                ('TypeOFJacket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.typeofjacket')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.version')),
                ('warenty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.warenty')),
            ],
        ),
        migrations.CreateModel(
            name='favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('rating', models.CharField(blank=True, choices=[('🧡', '🧡'), ('🧡💚', '🧡💚'), ('🧡💚🖤', '🧡💚🖤'), ('💙💚💛🧡', '💙💚💛🧡'), ('💙💚💛🧡💜', '💙💚💛🧡💜')], max_length=100, null=True)),
                ('football_rating', models.CharField(blank=True, choices=[('⚽', '⚽'), ('⚽⚽', '⚽⚽'), ('⚽⚽⚽', '⚽⚽⚽'), ('⚽⚽⚽⚽', '⚽⚽⚽⚽'), ('⚽⚽⚽⚽⚽', '⚽⚽⚽⚽⚽')], max_length=100, null=True)),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-review_date', '-rating'],
            },
        ),
        migrations.CreateModel(
            name='view_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
